create groups and make new users members of those groups. We need to accomplish this task using Ansible. Below you can find more information about the task.

There is already an inventory file ~/playbooks/inventory on jump host.

On jump host itself there is a list of users in ~/playbooks/data/users.yml file and there are two groups — admins and developers —that have list of different users. Create a playbook ~/playbooks/add_users.yml on jump host to perform the following tasks on app server 3 in Stratos DC.

a. Add all users given in the users.yml file on app server 3.

b. Also add developers and admins groups on the same server.

c. As per the list given in the users.yml file, make each user member of the respective group they are listed under.

d. Make sure home directory for all of the users under developers group is /var/www (not the default i.e /var/www/{USER}). Users under admins group should use the default home directory (i.e /home/devid for user devid).

e. Set password dCV3szSGNA for all of the users under developers group and 8FmzjvFU6S for of the users under admins group. Make sure to use the password given in the ~/playbooks/secrets/vault.txt file as Ansible vault password to encrypt the original password strings. You can use ~/playbooks/secrets/vault.txt file as a vault secret file while running the playbook (make necessary changes in ~/playbooks/ansible.cfg file).

f. All users under admins group must be added as sudo users. To do so, simply make them member of the wheel group as well.

Note: Validation will try to run the playbook using command ansible-playbook -i inventory add_users.yml so please make sure playbook works this way, without passing any extra arguments

---

- 
    name: Ansible adding user and groups   
    
    hosts: stapp03 
  
    become: yes
    
    tasks:
    
    -    
          name: creating admin group 
          group:
          name:
              admins
    -     
          name: creating dev group 
          group:
          name: 
              developers
    - 
          name: creating admims Users
          user:
           name: “{{ item }}”
           password: "{{ 'Rc5C9EyvbU' | password_hash('sha512') }}"
           groups: admins,wheel
          loop:
          - rob
          - david
          - joy      
    -     
          name: creating developer Users
          user:
           name: “{{ item }}”
           password: "{{ '8FmzjvFU6S' | password_hash('sha512') }}"
           home: /var/www/“{{ item }}”
           groups: developers  
          loop:
          - tim
          - ray
          - jim
          
          
---

name: Ansible adding user and groups   
hosts: stapp03 
become: yes

tasks:
    - name: "Add user group admin"
      inspur.sm.add_user_group:
        name: "admin"
        
    - name: "Add user group developer"
      inspur.sm.add_user_group:
        name: "developers"
          
    - name: Add several users to admin
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ 'ksH85UJjhb' | password_hash('sha512') }}"
        state: present
        groups: "wheel","admins"
      loop:
          - rob 
          - david
          - joy
    
    - name: Add several users to developers
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ 'ksH85UJjhb' | password_hash('sha512') }}"
        home: /var/www/“{{ item }}”
        state: present
        groups: "developers"
      loop:
          - tim 
          - ray
          - jim
