-
  name: Deploy a web application
  hosts: db_and_web_server
  tasks:
    - name: Install dependencies
      apt: name='{{ item }}' state=present
      with_items:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
      - python-mysqldb
    - name: Install mysql database
      apt: name={{ item }} state=present
      with_items:
      - mysql-server
      - mysql-client
    - name: create MySQL configuration file
      copy:
        content: |
          [client]
          user=root
          password="root"
        dest: "/etc/.my.cnf"
   - name: Start Mysql Service
     service:
        name: mysql
        state: started
        enabled: yes
   - name: Create Application Database
     mysql_db:
        name: employee_db
        state: present
   - name: Create Application DB User
     mysql_user: name='db_user' password='Passw0rd' priv='*.*:ALL' host='%' state='present'
   - name: Create Flask application
     pip: name='{{item}}' state=present
      with_items:
      - flask
      - flask-mysql 
   - name: copy application code
     copy:
       src: app.py
       dest: /opt/app.py
   - name: start application
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
