### Create a playbook.yml under /home/thor/ansible on jump host, an inventory file is already present under /home/thor/ansible directory on Jump Server itself.
< Create an empty file blog.txt under /opt/data/ directory on app server 1. 
Set some acl properties for this file. Using acl provide read '(r)' permissions to group tony (i.e entity is tony and etype is group).
< Create an empty file story.txt under /opt/data/ directory on app server 2. 
Set some acl properties for this file. Using acl provide read + write '(rw)' permissions to user steve (i.e entity is steve and etype is user).
< Create an empty file media.txt under /opt/data/ on app server 3. 
Set some acl properties for this file. Using acl provide read + write '(rw)' permissions to group banner (i.e entity is banner and etype is group).

Note: Validation will try to run the playbook using command ansible-playbook -i inventory playbook.yml
---
thor@jump_host ~/ansible$ cat inventory 
stapp01 ansible_host=172.16.238.10 ansible_ssh_pass=Ir0nM@n ansible_user=tony
stapp02 ansible_host=172.16.238.11 ansible_ssh_pass=Am3ric@ ansible_user=steve
stapp03 ansible_host=172.16.238.12 ansible_ssh_pass=BigGr33n ansible_user=bannerthor@jump_host ~/ansible$ 

---

-   name: 'Create empty file'
    hosts: stapp01
    become: yes
    tasks:
    -  name: 'create empty file'
       command: touch /opt/data/blog.txt
    -  name: Sets default ACL for tony
       acl:
         path: /opt/data/
         entity: tony
         etype: group
         permissions: r
         default: yes
         state: present
-   name: 'Create empty file'
    hosts: stapp02
    become: yes
    tasks:
    -  name: 'create empty file'
       command: touch /opt/data/story.txt
    -  name: Sets default ACL for steve
       acl:
         path: /opt/data/
         entity: steve
         etype: user
         permissions: rw
         default: yes
         state: present
-   name: 'Create empty file'
    hosts: stapp03
    become: yes
    tasks:
    -  name: 'create empty file'
       command: touch /opt/data/media.txt
    -  name: Sets default ACL for banner
       acl:
         path: /opt/data/
         entity: banner
         etype: group
         permissions: rw
         default: yes
         state: present
         
---
Verify: Check that the files are created by running
      
thor@jump_host ~/ansible$  ansible all -a "ls -ltr /opt/data/" -i inventory
stapp01 | CHANGED | rc=0 >>
total 0
-rw-r--r-- 1 root root 0 Sep  5 03:14 blog.txt
stapp03 | CHANGED | rc=0 >>
total 0
-rw-r--r-- 1 root root 0 Sep  5 03:14 media.txt
stapp02 | CHANGED | rc=0 >>
total 0
-rw-r--r-- 1 root root 0 Sep  5 03:14 story.txt
