We need to accomplish this task using Ansible. Below you can find more information about the task.

There is already an inventory file ~/playbooks/inventory on jump host.

On jump host itself there is a list of users in ~/playbooks/data/users.yml file and there are two groups — admins and developers —that have list of different users. Create a playbook ~/playbooks/add_users.yml on jump host to perform the following tasks on app server 2 in Stratos DC.

a. Add all users given in the users.yml file on app server 2.

b. Also add developers and admins groups on the same server.

c. As per the list given in the users.yml file, make each user member of the respective group they are listed under.

d. Make sure home directory for all of the users under developers group is /var/www (not the default i.e /var/www/{USER}). Users under admins group should use the default home directory (i.e /home/devid for user devid).

e. Set password dCV3szSGNA for all of the users under developers group and YchZHRcLkL for of the users under admins group. Make sure to use the password given in the ~/playbooks/secrets/vault.txt file as Ansible vault password to encrypt the original password strings. You can use ~/playbooks/secrets/vault.txt file as a vault secret file while running the playbook (make necessary changes in ~/playbooks/ansible.cfg file).

f. All users under admins group must be added as sudo users. To do so, simply make them member of the wheel group as well.

Note: Validation will try to run the playbook using command ansible-playbook -i inventory add_users.yml
--
~/playbooks$ cat ansible.cfg 
[defaults]
host_key_checking = False
vault_password_file = /home/thor/playbooks/secrets/vault.txt

---                                                                                                              
- name: Ansbile Add User & Group                                                                       
  hosts: stapp01                                                                                               
  become: yes                                                                                                    
  tasks:                                                                                                         
  - name: Creating Admin Groups                                                                                  
    group:                                                                                                       
     name:                                                                                                       
      admins                                                                                                     
     state: present                                                                                              
  - name: Creating Dev Groups                                                                                    
    group:                                                                                                       
     name:                                                                                                       
      developers                                                                                                 
     state: present                                                                                              
  - name: Creating Admins Group Users                                                                            
    user:                                                                                                        
     name: "{{ item }}"                                                                                          
     password: "{{ '8FmzjvFU6S' | password_hash ('sha512') }}"                                                   
     groups: admins,wheel
     state: present                                                                                              
    loop:                                                                                                        
    - rob                                                                                                                                                                                                               
    - david  
    - joy
  - name: Creating Developers Group Users                                                                        
    user:                                                                                                        
     name: "{{ item }}"                                                                                          
     password: "{{ 'dCV3szSGNA' | password_hash ('sha512') }}"                                                   
     home: "/var/www/{{ item }}"                                                                                             
     group: developers                                                                                           
     state: present                                                                                              
    loop:                                                                                                        
    - tim                                                                                                        
    - ray                                                                                                       
    - jim                                                                                                       
