# Create a playbook index.yml under /home/thor/playbooks directory on jump host. 
# Using blockinfile Ansible module create a file facts.txt under /root directory on all app servers and add the following given block in it. 
# You will need to enable facts gathering for this task.
# Ansible managed node IP is <default ipv4 address>
# (You can obtain default ipv4 address from Ansible's gathered facts by using the correct Ansible variable while taking into account Jinja2 syntax)

# Install httpd server on all apps. After that make a copy of facts.txt file as index.html under /var/www/html directory. 
# Make sure to start httpd service after that.


---

-

  hosts: stapp01, stapp02, stapp03

  gather_facts: true

  become: yes

  become_method: sudo

  tasks:

    - name: create a  file using blockinfile

      blockinfile:

       create: yes

       path: /root/facts.txt

       block: |

         Ansible managed node IP is {{ ansible_default_ipv4.address }}

    - name: Install apache packages

      package:

       name: httpd

    - name: file copy

      shell: cp /root/facts.txt /var/www/html/index.html

    - name: ensure httpd is running

      systemd:

       name: httpd

       state: restarted
      
  ----
    
    thor@jump_host ~/playbooks$ curl http://stapp01
# BEGIN ANSIBLE MANAGED BLOCK

Ansible managed node IP is 172.16.238.10
# END ANSIBLE MANAGED BLOCK
thor@jump_host ~/playbooks$ curl http://stapp02
# BEGIN ANSIBLE MANAGED BLOCK

Ansible managed node IP is 172.16.238.11
# END ANSIBLE MANAGED BLOCK
thor@jump_host ~/playbooks$ curl http://stapp03
# BEGIN ANSIBLE MANAGED BLOCK

Ansible managed node IP is 172.16.238.12
# END ANSIBLE MANAGED BLOCK
thor@jump_host ~/playbooks$ 
