a. Create an inventory file ~/playbook/inventory on jump host and add all app servers in it.

b. Create a playbook ~/playbook/playbook.yml to create a blank file /home/webapp.txt on all app servers.

c. The /home/webapp.txt file permission must be 0744.

d. The user/group owner of file /home/webapp.txt must be tony on app server 1, steve on app server 2 and banner on app server 3.

---
thor@jump_host ~/playbook$ vi inventory

stapp01  ansible_host=172.16.238.10   ansible_connection=ssh   ansible_user=tony ansible_ssh_pass=Ir0nM@n
stapp02  ansible_host=172.16.238.11   ansible_connection=ssh   ansible_user=steve ansible_ssh_pass=Am3ric@
stapp03  ansible_host=172.16.238.12   ansible_connection=ssh   ansible_user=banner ansible_ssh_pass=BigGr33n

thor@jump_host ~/playbook$ vi playbook.yml

- name: Create file in appservers
  hosts: stapp01, stapp02, stapp03
  become: yes
  tasks:
    - name: Create the file and set properties
      file:
        path: /home/webapp.txt
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0744"
        state: touch
        
 thor@jump_host ~/playbook$ ansible-playbook -i inventory playbook.yml

PLAY [Create file in appservers] *****************************************************

TASK [Gathering Facts] ***************************************************************
ok: [stapp01]
ok: [stapp03]
ok: [stapp02]

TASK [Create the file and set properties] ********************************************
changed: [stapp01]
changed: [stapp03]
changed: [stapp02]

PLAY RECAP ***************************************************************************
stapp01                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
stapp02                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
stapp03                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

thor@jump_host ~/playbook$ ansible all -a "ls -ltr /home/" -i inventory
stapp02 | CHANGED | rc=0 >>
total 8
drwx------ 1 ansible ansible 4096 Oct 15  2019 ansible
drwx------ 1 steve   steve   4096 Mar 29 01:52 steve
-rwxr--r-- 1 steve   steve      0 Mar 29 01:53 webapp.txt
stapp01 | CHANGED | rc=0 >>
total 8
drwx------ 1 ansible ansible 4096 Oct 15  2019 ansible
drwx------ 1 tony    tony    4096 Mar 29 01:52 tony
-rwxr--r-- 1 tony    tony       0 Mar 29 01:53 webapp.txt
stapp03 | CHANGED | rc=0 >>
total 8
drwx------ 1 ansible ansible 4096 Oct 15  2019 ansible
drwx------ 1 banner  banner  4096 Mar 29 01:52 banner
-rwxr--r-- 1 banner  banner     0 Mar 29 01:53 webapp.txt

