 > <
Ansible Playbooks
You are assigned a task to restart a number of servers in a particular sequence. 
The sequence and the commands to be used are given below. Note that the commands should be run on respective servers only.
Refer to the inventory file and update the playbook to create the below sequence.

Note: Use the description below to name the plays and tasks.

Stop the web services on web server nodes - service httpd stop
Shutdown the database services on db server nodes - service mysql stop
Restart all servers (web and db) at once - /sbin/shutdown -r
Start the database services on db server nodes - service mysql start
Start the web services on web server nodes - service httpd start

----

# Sample Inventory File

# Web Servers
sql_db1 ansible_host=sql01.xyz.com ansible_connection=ssh ansible_user=root ansible_ssh_pass=Lin$Pass
sql_db2 ansible_host=sql02.xyz.com ansible_connection=ssh ansible_user=root ansible_ssh_pass=Lin$Pass
web_node1 ansible_host=web01.xyz.com ansible_connection=ssh ansible_user=administrator ansible_ssh_pass=Win$Pass
web_node2 ansible_host=web02.xyz.com ansible_connection=ssh ansible_user=administrator ansible_ssh_pass=Win$Pass
web_node3 ansible_host=web03.xyz.com ansible_connection=ssh ansible_user=administrator ansible_ssh_pass=Win$Pass

[db_nodes]
sql_db1
sql_db2

[web_nodes]
web_node1
web_node2
web_node3

[all_nodes:children]
db_nodes
web_nodes

----

-
    name: 'Stop the web services on web server nodes'
    hosts: web_nodes
    tasks:
        -
            name: 'Stop the web services on web server nodes'
            command: 'service httpd stop'
            
 ----
 solution
 ----
 
 -
    name: 'Stop the web services on web server nodes'
    hosts: web_nodes
    tasks:
        -
            name: 'Stop the web services on web server nodes'
            command: 'service httpd stop'
-
    name: 'Shutdown the database services on db server nodes '
    hosts: db_nodes
    tasks:
        -
            name: 'Stop the web services on web server nodes'
            command: 'service mysql stop'
-
    name: 'Restart all servers (web and db) at once'
    hosts: all_nodes
    tasks:
        -
            name: 'Restart all servers (web and db) at once'
            command: '/sbin/shutdown -r'
-
    name: 'Start the database services on db server node'
    hosts: db_nodes
    tasks:
        -
            name: 'Start the database services on db server node'
            command: 'service mysql start'
-
    name: 'Start the web services on web server nodes'
    hosts: web_nodes
    tasks:
        -
            name: 'Start the web services on web server nodes'
            command: 'service httpd start'
